# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TljK1poENURu7N8lWGDeqDfUudcYNsZu
"""

# Google Colab Setup and Dependency Installation
!pip install -q pandas numpy scikit-learn matplotlib seaborn

import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import TimeSeriesSplit
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import matplotlib.pyplot as plt
import seaborn as sns
import os

# Suppress warnings for cleaner output
import warnings
warnings.filterwarnings('ignore')

# Download the zipped dataset directly from the UCI archive
!curl https://archive.ics.uci.edu/ml/machine-learning-databases/00482/dataset.zip --create-dirs -o./data/dataset.zip

# Clean up previous extraction and ensure target directory exists
!rm -rf ./data/Bike-Sharing-Dataset
!mkdir -p ./data

# Unzip the downloaded file directly into the data directory by changing context
current_dir = os.getcwd()
os.chdir('./data/')
!unzip -o dataset.zip
os.chdir(current_dir)

# Verify extraction (optional, but helpful for debugging)
print('Contents of ./data/ after extraction:')
!ls -R ./data/

# Load the extracted CSV (assuming 'dataset.csv' is the target file within the unzipped folder)
df = pd.read_csv('./data/dataset.csv')

# Re-load the dataframe
df = pd.read_csv('./data/dataset.csv')

# The actual datetime column in this dataset is 'LastUpdated'
datetime_col = 'LastUpdated'

print(f"Using column '{datetime_col}' for datetime features.")

# Convert to datetime - specify format if needed or let pandas infer
df[datetime_col] = pd.to_datetime(df[datetime_col], errors='coerce')

# Drop rows where datetime parsing failed and sort
df = df.dropna(subset=[datetime_col])
df = df.sort_values(by=datetime_col).reset_index(drop=True)

# Extract temporal features
df['Hour'] = df[datetime_col].dt.hour
df['DayOfWeek'] = df[datetime_col].dt.dayofweek
df['Month'] = df[datetime_col].dt.month

# Check if we have data now
print(f'Rows remaining: {len(df)}')
display(df.head())

"""# Task
Prepare the Birmingham Parking dataset from "./data/dataset.csv" for time series forecasting by applying cyclical sine/cosine encoding to 'Hour', 'DayOfWeek', and 'Month' features, and one-hot encoding the 'SystemCodeNumber' column. Train a RandomForestRegressor (n_estimators=100, max_depth=15) to predict 'Occupancy' using a 5-fold TimeSeriesSplit cross-validation, and calculate the average MSE, MAE, and R2 metrics to summarize the model's performance.

## Cyclical Encoding and Feature Cleanup

### Subtask:
Apply cyclical transformations to temporal features and remove non-numeric or redundant columns.

**Reasoning**:
I will perform cyclical encoding on the temporal features to capture their periodic nature and remove the original columns along with the raw timestamp.
"""

import numpy as np

# Define periods
periods = {
    'Hour': 24,
    'DayOfWeek': 7,
    'Month': 12
}

# Apply cyclical encoding
for col, max_val in periods.items():
    df[f'{col}_sin'] = np.sin(2 * np.pi * df[col] / max_val)
    df[f'{col}_cos'] = np.cos(2 * np.pi * df[col] / max_val)

# Drop original temporal features and the raw timestamp
cols_to_drop = ['Hour', 'DayOfWeek', 'Month', 'LastUpdated']
df = df.drop(columns=cols_to_drop)

print(f'Columns after cyclical encoding and cleanup: {df.columns.tolist()}')
display(df.head())

"""## Spatial Categorical Encoding

### Subtask:
Apply one-hot encoding to the 'SystemCodeNumber' column and define the feature and target sets.

**Reasoning**:
I will perform one-hot encoding on the 'SystemCodeNumber' column and prepare the feature matrix X and target vector y as instructed.
"""

import pandas as pd

# 1. One-hot encode 'SystemCodeNumber'
df_encoded = pd.get_dummies(df, columns=['SystemCodeNumber'], prefix='ID')

# 2. Define the target variable y
y = df_encoded['Occupancy']

# 3. Define the feature matrix X
# We drop 'Occupancy' (target) and 'Capacity' (static attribute/potential leakage)
X = df_encoded.drop(columns=['Occupancy', 'Capacity'])

# 4. Display shapes to confirm readiness
print(f'Shape of feature matrix X: {X.shape}')
print(f'Shape of target vector y: {y.shape}')

# Display first few rows of the final feature set
display(X.head())

"""## TimeSeriesSplit and Model Training

### Subtask:
Train and evaluate a RandomForestRegressor using 5-fold TimeSeriesSplit cross-validation on the prepared features and target.

**Reasoning**:
I will now implement the TimeSeriesSplit cross-validation and train the RandomForestRegressor as instructed, collecting metrics for each fold.
"""

from sklearn.model_selection import TimeSeriesSplit
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

# 1. Initialize TimeSeriesSplit with 5 folds
tscv = TimeSeriesSplit(n_splits=5)

# 2. Initialize the RandomForestRegressor
rf_model = RandomForestRegressor(n_estimators=100, max_depth=15, random_state=42, n_jobs=-1)

# 3. Initialize lists to store metrics
mse_scores = []
mae_scores = []
r2_scores = []

print(f'Starting TimeSeriesSplit training on {len(X)} samples...\n')

# 4. Cross-validation loop
for fold, (train_index, test_index) in enumerate(tscv.split(X), 1):
    # Split data
    X_train, X_test = X.iloc[train_index], X.iloc[test_index]
    y_train, y_test = y.iloc[train_index], y.iloc[test_index]

    # Fit model
    rf_model.fit(X_train, y_train)

    # Predict
    y_pred = rf_model.predict(X_test)

    # Calculate metrics
    mse = mean_squared_error(y_test, y_pred)
    mae = mean_absolute_error(y_test, y_pred)
    r2 = r2_score(y_test, y_pred)

    # Store metrics
    mse_scores.append(mse)
    mae_scores.append(mae)
    r2_scores.append(r2)

    print(f'Fold {fold}:')
    print(f'  MSE: {mse:.4f}')
    print(f'  MAE: {mae:.4f}')
    print(f'  R2 : {r2:.4f}')
    print('-' * 20)

"""## Performance Summary

### Subtask:
Calculate and report the average MSE, MAE, and R2 metrics from the cross-validation to summarize the model's performance.

**Reasoning**:
I will calculate the average of the performance metrics stored in the lists from the previous step and provide a summary and interpretation of the model's performance.
"""

import numpy as np

# 1. Calculate the mean for each metric
avg_mse = np.mean(mse_scores)
avg_mae = np.mean(mae_scores)
avg_r2 = np.mean(r2_scores)

# 2. Print the formatted summary
print('--- Final Model Performance Summary ---')
print(f'Average Mean Squared Error (MSE): {avg_mse:.4f}')
print(f'Average Mean Absolute Error (MAE): {avg_mae:.4f}')
print(f'Average R-squared (R2):           {avg_r2:.4f}')
print('-' * 39)

# 3. Brief interpretation
if avg_r2 > 0.8:
    interpretation = "The model shows high predictive power with an R2 above 0.8, suggesting it effectively captures the variance in parking occupancy."
else:
    interpretation = "The model performance is moderate; further feature engineering or hyperparameter tuning might be required to improve accuracy."

print(f'Interpretation: {interpretation}')

"""## Summary:

### Q&A

**How was the temporal data prepared for the machine learning model?**
The temporal features ('Hour', 'DayOfWeek', and 'Month') were transformed using cyclical sine and cosine encoding. This method preserves the periodic nature of time (e.g., ensuring hour 23 is recognized as being close to hour 0).

**What model was used and how was it evaluated?**
A `RandomForestRegressor` with 100 estimators and a maximum depth of 15 was used. To respect the chronological nature of the data, the model was evaluated using a 5-fold `TimeSeriesSplit` cross-validation.

### Data Analysis Key Findings

*   **Feature Engineering:** The dataset was expanded to 36 features, including 6 cyclical time features and 30 one-hot encoded variables representing unique parking locations (`SystemCodeNumber`).
*   **Model Accuracy:** The model achieved a high average **R-squared (R2) score of 0.9214**, indicating that it can explain over 92% of the variance in parking occupancy.
*   **Error Metrics:**
    *   The **Average Mean Absolute Error (MAE)** was **128.01**, which serves as a measure of the average deviation in predicted parking spots.
    *   The **Average Mean Squared Error (MSE)** was **34,685.93**.
*   **Consistency:** After the first fold, the model demonstrated stable performance with R2 scores consistently exceeding 0.92, suggesting it learned the temporal patterns effectively as more data became available in the training window.

### Insights or Next Steps

*   **Feature Importance Analysis:** A logical next step would be to extract and visualize feature importance from the Random Forest model to determine whether specific hours or specific parking locations are the primary drivers of occupancy fluctuations.
*   **Lagged Features:** To further improve the model, especially for short-term forecasting, incorporating lagged versions of the 'Occupancy' variable (e.g., occupancy from 1 or 2 hours prior) could help capture immediate trends that cyclical time features might miss.

"""
